#!/bin/sh
echo "analyze..."
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

if [ -z "$files" ]; then
  echo "No Go files to check. Formatting check passed successfully."
  exit 0
fi

unformatted=$(gofmt -l "$files")

if [ -n "$unformatted" ]; then
  echo "unformatted"
  echo "$unformatted"
  echo "please execute gofmt -w <filename>"
  exit 1
fi
